#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= board_ijb_skt.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= platform_ijb_skt_bt.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= platform_ijb_skt_camera.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= platform_ijb_skt_input.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= platform_ijb_skt_misc.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= platform_ijb_skt_panel.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= platform_ijb_skt_snd.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= gpiomux_ijb_skt.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= devices_ijb_skt.o
