#
# Makefile for the broadcast(TDMB) RF/BB core.
#

obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_tdmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8050)		+= fc8050/
#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= lg2102/
#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= t3900/
