#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= board_i_skt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_bt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_camera.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_input.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_misc.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= platform_i_skt_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= gpiomux_i_skt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= devices_i_skt.o
