#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD)	+= devices_lge.o
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= i_skt/
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= ijb_lgu/
obj-$(CONFIG_MACH_LGE_IJB_BOARD_SKT)	+= ijb_skt/
