#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= board_ijb_lgu.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= platform_ijb_lgu_bt.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= platform_ijb_lgu_camera.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= platform_ijb_lgu_input.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= platform_ijb_lgu_panel.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= platform_ijb_lgu_snd.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= gpiomux_ijb_lgu.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_LGU)	+= devices_ijb_lgu.o
